# Generated by Django 6.0.3 on 2026-03-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='glassesmodel',
            name='position_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='glassesmodel',
            name='position_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='glassesmodel',
            name='position_z',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='glassesmodel',
            name='rotation_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='glassesmodel',
            name='rotation_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='glassesmodel',
            name='rotation_z',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='glassesmodel',
            name='scale',
            field=models.FloatField(default=1.0),
        ),
    ]
