# Generated by Django 6.0.3 on 2026-03-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='glassesmodel',
            name='calibration_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='glassesmodel',
            name='calibration_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('ai', 'AI'), ('fallback', 'Fallback')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='glassesmodel',
            name='calibration_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='glassesmodel',
            name='last_calibrated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
